Feature/reports
ApplETS/Backend-Hello pull request #22
Opened 2024-03-22 22:00 UTC by JonathanDuvalV

Added two new routes, one public route for reporting an event
![image](https://github.com/ApplETS/Backend-Hello/assets/45638733/2e15e087-93ee-4cc8-9a67-e9919572804e)

and a protected route for moderators to fetch the reports
![image](https://github.com/ApplETS/Backend-Hello/assets/45638733/65f747ea-3540-492e-8e6b-20c8216913b1)

2024-03-23 03:06 UTC, MysticFragilist requested changes
Aussi, j'ai deux comments sur les reports:

1- Il faudrait que le endpoint pour créer un Report soit RateLimited pour plusieurs valeurs:
    - Un temps de Window configurable (.env):  https://www.c-sharpcorner.com/blogs/rate-limiting-in-net-70
    - S'assurer d'essayer du mieux possible de réduire les requêtes en double, (par exemple faire un check sur l'adresse IP pourrait être possible mais pt pas pratique si 70% des gens report depuis le réseau de l'école). **On pourra en reparler je sais pas si c'est faisable**. Exemple: https://stackoverflow.com/questions/76309904/net-7-rate-limiting-rate-limit-by-ip
    - Peut-être avoir 10 secondes par défaut et un max PermitLimit de 4 mettons? donc 1 report au 2.5s environ.

2- Je me demandais si on voulait pas avoir un genre de check s'il y a plus de X reports (par exemple 10) sur la même annonce on envoit un courriel au modérateur pour aller review l'annonce pour être sûr de sa validité. Il faudrait qu'une fois qu'un courriel se fait envoyer au modérateur, il ne se renvoit plus jamais.

Si jamais le #2 est trop chiant, tu peux créer une issue pour le faire mais je pense le #1 faudrait le faire live si on veut avoir le endpoint online.

2024-03-23 19:48 UTC, JonathanDuvalV commented on core/Services/ReportService.cs
> +            Date = request.Date,
L'entity l'avais deja donc je me suis dis que il avait peut-etre une raison qu'on l'aille 😅 mais c'est good je vais l'enlever!

2024-03-23 21:16 UTC, JonathanDuvalV commented on core/Services/ReportService.cs
> +            Reason = request.Reason,
True ca pourrait etre nice, je vais regarder pour ajouter ca!

2024-03-23 21:20 UTC, JonathanDuvalV commented on core/Controllers/ModeratorEventsController.cs
> +        EnsureIsModerator();
Quand la PR avec les policy va etre merger, je vais retirer ca!

2024-03-23 21:38 UTC, JonathanDuvalV commented
> 1- Il faudrait que le endpoint pour créer un Report soit RateLimited sur plusieurs valeurs: - Un temps de Window configurable (.env): https://www.c-sharpcorner.com/blogs/rate-limiting-in-net-70 - S'assurer d'essayer du mieux possible de réduire les requêtes en double, (par exemple faire un check sur l'adresse IP pourrait être possible mais pt pas pratique si 70% des gens report depuis le réseau de l'école). **On pourra en reparler je sais pas si c'est faisable**. Exemple: https://stackoverflow.com/questions/76309904/net-7-rate-limiting-rate-limit-by-ip - Peut-être avoir 10 secondes par défaut et un max PermitLimit de 4 mettons? donc 1 report au 2.5s environ. Si c'est configurable après ça peut être worth je pense.

Pour le duplicate, je crois pas que c'est possible avec le rate limiter de .NET. J'ai ajouté un AvoidDuplicate dans le ReportService qui vérifie si un report avec une raison identique sur la même publication a été envoyé dans le même time window que le rate limiter.

2024-03-24 01:47 UTC, MysticFragilist requested changes
Mini comment sinon all good! LGTM quand t'auras fix!!

2024-03-24 01:47 UTC, MysticFragilist commented on core/Data/Enums/ReportCategory.cs
> +[Flags]
On peut enlever Flags je pense, ça fait moyen du sens que tu puisses combiner des catégories. (Si on veut le garder faudrait que les numéros soit 1, 2, 4, 8) pour avoir des shift de bits cohérents!
```suggestion
```

2024-03-24 01:47 UTC, MysticFragilist commented on core/Extensions/RateLimiterExtension.cs
> +    public static IServiceCollection AddRateLimiters(this IServiceCollection services)
Niice bonne idée!

2024-03-24 01:47 UTC, MysticFragilist commented on core/Services/ReportService.cs
> +        return reports.Any(r => r.Reason == request.Reason && r.PublicationId == publicationId && r.Category == request.Category);
Bonne idée!

2024-03-24 16:25 UTC, merged