Toggle an organizer's isActive state
ApplETS/Backend-Hello pull request #23
Opened 2024-03-22 22:45 UTC by JonathanDuvalV

Added a route to toggle the isActive property of an Organizer.

![image](https://github.com/ApplETS/Backend-Hello/assets/45638733/5ed0fc5e-50d6-4deb-9fab-7ad6936ff475)

An organizer with an isActive set to false will get Unauthorized exceptions for api calls related to creating/updating/deleting his events

2024-03-23 00:46 UTC, JonathanDuvalV commented
Finalement c'est pas fini, il faut que j'envoies la raison de désactivation par courriel

2024-03-23 02:09 UTC, MysticFragilist requested changes

2024-03-23 18:49 UTC, JonathanDuvalV commented on core/Controllers/OrganizerEventsController.cs
> +    }
Bonne idée, je vais regarder ca!

2024-03-24 01:53 UTC, MysticFragilist approved these changes
LGTM! vraiment cool le système de policies! 😄 J'avais jamais utilisé ça avant c'est clean quand même!

2024-03-24 16:17 UTC, merged