PS-148 notification email
ApplETS/Backend-Hello pull request #41
Opened 2024-04-08 16:44 UTC by MysticFragilist

2024-04-08 20:12 UTC, camillebrulotte requested changes

2024-04-08 20:20 UTC, HugoMigner commented on core/Services/Jobs/ProcessNotificationByEmailJob.cs
> +            await Console.Out.WriteLineAsync($"[NotificationByEmailJob] {emailsCount} emails were sent out");
Ça c'est tu nécessaire? 😮

2024-04-08 20:59 UTC, HugoMigner commented on core/Services/NotificationService.cs
> +                    HeaderText = "Une nouvelle publication a été publié de un de vos organisations préférées! Voici un aperçu de l'annonce ",
publiée* aussi

2024-04-10 18:50 UTC, MysticFragilist commented on core/Services/NotificationService.cs
> +                "Subject",
```suggestion
                "Nouvelle publication de {organizer.Organization}",
```

2024-04-10 18:50 UTC, MysticFragilist commented on core/Services/NotificationService.cs
> +                    HeaderText = "Une nouvelle publication a été publié par {organizer.Organization}! Voici un aperçu de l'annonce ",
```suggestion
                    HeaderText = "Une nouvelle publication a été publiée par {organizer.Organization}! Voici un aperçu de l'annonce ",
```

2024-04-10 18:50 UTC, MysticFragilist commented on core/Services/SubscriptionService.cs
> +    }
```suggestion
```

2024-04-10 18:50 UTC, MysticFragilist commented on emails/Services/Abstractions/IEmailService.cs
> +
```suggestion
```

2024-04-10 18:50 UTC, MysticFragilist commented on emails/Services/EmailService.cs
> +
```suggestion
```

2024-04-10 18:54 UTC, MysticFragilist commented on core/Services/Jobs/ProcessNotificationByEmailJob.cs
> +            await Console.Out.WriteLineAsync($"[NotificationByEmailJob] {emailsCount} emails were sent out");
Ouii pour logger des info! Mais tu me fais penser que c'est mieux de use le logger provided

2024-04-12 13:15 UTC, Udito3 approved these changes
LGTM

2024-04-12 13:27 UTC, merged